# Generated by deb2nix 0.1.0 (profile: chromium-browser).
# Review before use. Not intended for publishing into nixpkgs.
# Hash-pinned. Unfree, if any, is explicit via allowUnfreePredicate
# (Tim approval 2026-09-10: Chrome, Edge, VS Code, Grok Bot, DisplayLink EULAs).
{
  description = "The web browser from Google";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {
        inherit system;
        config.allowUnfreePredicate = pkg:
          builtins.elem (nixpkgs.lib.getName pkg) [ "google-chrome-stable" ];
        # Tim 2026-09-10: EULAs accepted. Predicate still pname-scoped (not allowUnfree = true).
      };
    in {
      packages.${system} = rec {
        default = pkgs.callPackage ./package.nix { };
        "google-chrome-stable" = default;
      };
    };
}
