# Generated by deb2nix 0.1.0 (profile: driver).
# Review before use. Not intended for publishing into nixpkgs.
# Hash-pinned. Unfree, if any, is explicit via allowUnfreePredicate
# (Tim approval 2026-09-10: Chrome, Edge, VS Code, Grok Bot, DisplayLink EULAs).
# NixOS module stub — DisplayLink / kernel drivers.
# This file is NOT imported by package.nix. It documents how a human would
# wire nixpkgs hardware.video.displaylink after reviewing LIMITATIONS.md.
# deb2nix will not insmod, will not run DKMS, will not modify host machines.

{ config, lib, pkgs, ... }:

{
  # Unfree EULA accepted 2026-09-10 (Tim). Still do not enable this blindly:
  # EVDI is a kernel module. Enable only on a NixOS host you intend to reboot.
  #
  # nixpkgs: hardware.video.displaylink.enable
  #          + evdi + requireFile for the vendor blob on some versions.
  #
  # Example (commented — not activated by generating this tree):
  #
  # nixpkgs.config.allowUnfreePredicate = pkg:
  #   builtins.elem (lib.getName pkg) [ "displaylink-driver" "displaylink" "evdi" ];
  # hardware.video.displaylink.enable = false;
  # boot.extraModulePackages = [ ]; # do not add evdi from this stub

  assertions = [
    {
      assertion = true;
      message = "deb2nix DisplayLink stub: kernel/DKMS not enabled";
    }
  ];
}
