# Generated by deb2nix 0.1.0 (profile: driver).
# Review before use. Not intended for publishing into nixpkgs.
# Hash-pinned. Unfree, if any, is explicit via allowUnfreePredicate
# (Tim approval 2026-09-10: Chrome, Edge, VS Code, Grok Bot, DisplayLink EULAs).
# This file is documentation for a future profile implementation.
# package.nix throws until the profile is fully implemented.
#
# profile: driver
# subtype: displaylink
#
# Phase 3 prep. Synaptics EULA accepted 2026-09-10; still never insmod/DKMS. See LIMITATIONS.md + nixos-module.stub.nix.
#
# Suggested fetch:
#   src = fetchurl { url = "..."; hash = "sha256-zHVC+5aQb5cPwTVO2DwKhRVH96RoCa2zNlmKDjGxWKM="; };
