# Generated by deb2nix 0.1.0 (profile: driver).
# Review before use. Not intended for publishing into nixpkgs.
# Hash-pinned. Unfree, if any, is explicit via allowUnfreePredicate
# (Tim approval 2026-09-10: Chrome, Edge, VS Code, Grok Bot, DisplayLink EULAs).
# Classifier evidence:
# {
#   "profile": "driver",
#   "confidence": "high",
#   "reasons": [
#     "name/description matches driver token 'displaylink'",
#     "name/description matches driver token 'evdi'",
#     "name/description matches driver token 'dkms'"
#   ],
#   "evidence": {
#     "kernel_modules": [],
#     "hints": [
#       "name/description matches driver token 'displaylink'",
#       "name/description matches driver token 'evdi'",
#       "name/description matches driver token 'dkms'"
#     ]
#   },
#   "subtype": "displaylink",
#   "warnings": [
#     "deb2nix will not emit an expression that loads kernel modules or installs DKMS (including DisplayLink/EVDI)."
#   ]
# }

{
  lib,
}:

throw "deb2nix classified 'displaylink-driver' as profile 'driver'. name/description matches driver token 'displaylink'; name/description matches driver token 'evdi'; name/description matches driver token 'dkms'. deb2nix will not emit an expression that loads kernel modules, installs DKMS, or activates DisplayLink/EVDI. That is intentional. deb2nix will not emit an expression that loads kernel modules or installs DKMS (including DisplayLink/EVDI)."
