"""Emit flake.nix / package.nix / default.nix / report.json for a profile."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent

from deb2nix import __version__
from deb2nix.classify import Classification
from deb2nix.control import Control
from deb2nix.locate import MappingResult
from deb2nix.nixlang import nix_ident, nix_indented_string, nix_string


NIXPKGS_LICENSE = {
    "mit": "lib.licenses.mit",
    "expat": "lib.licenses.mit",
    "bsd-2-clause": "lib.licenses.bsd2",
    "bsd-3-clause": "lib.licenses.bsd3",
    "apache-2.0": "lib.licenses.asl20",
    "asl2.0": "lib.licenses.asl20",
    "gpl-2": "lib.licenses.gpl2Only",
    "gpl-2.0": "lib.licenses.gpl2Only",
    "gpl-2+": "lib.licenses.gpl2Plus",
    "gpl-2.0+": "lib.licenses.gpl2Plus",
    "gpl-3": "lib.licenses.gpl3Only",
    "gpl-3.0": "lib.licenses.gpl3Only",
    "gpl-3+": "lib.licenses.gpl3Plus",
    "gpl-3.0+": "lib.licenses.gpl3Plus",
    "lgpl-2.1": "lib.licenses.lgpl21Only",
    "lgpl-2.1+": "lib.licenses.lgpl21Plus",
    "lgpl-3": "lib.licenses.lgpl3Only",
    "lgpl-3.0+": "lib.licenses.lgpl3Plus",
    "mpl-2.0": "lib.licenses.mpl20",
    "isc": "lib.licenses.isc",
    "zlib": "lib.licenses.zlib",
}


@dataclass
class EmitContext:
    control: Control
    classification: Classification
    mapping: MappingResult
    src_kind: str  # url | local
    src_url: str | None
    src_hash: str
    src_filename: str
    system: str
    pname: str
    unfree: bool
    license_expr: str
    main_program: str | None
    binaries: list[str]
    needed: list[str]


def license_expr_for(control: Control) -> tuple[str, bool]:
    raw = (control.license or "").strip()
    key = raw.lower().split(",")[0].strip()
    if key in NIXPKGS_LICENSE and not control.is_unfree():
        return NIXPKGS_LICENSE[key], False
    if control.is_unfree() or not raw:
        # Unknown Debian License field: treat as unfree so allowUnfree is explicit.
        if not raw:
            return "lib.licenses.unfree", True
        return "lib.licenses.unfree", True
    return "lib.licenses.unfree", True


def guess_main_program(control: Control, binaries: list[str]) -> str | None:
    names = []
    for rel in binaries:
        if rel.startswith("usr/bin/") or rel.startswith("bin/"):
            names.append(Path(rel).name)
    if not names:
        for rel in binaries:
            names.append(Path(rel).name)
    pkg = control.package
    if pkg in names:
        return pkg
    if names:
        return names[0]
    return nix_ident(pkg)


def emit_all(out_dir: Path, ctx: EmitContext) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    package = _emit_package(ctx)
    (out_dir / "package.nix").write_text(package, encoding="utf-8")
    written.append(out_dir / "package.nix")
    default = _emit_default(ctx)
    (out_dir / "default.nix").write_text(default, encoding="utf-8")
    written.append(out_dir / "default.nix")
    flake = _emit_flake(ctx)
    (out_dir / "flake.nix").write_text(flake, encoding="utf-8")
    written.append(out_dir / "flake.nix")
    report = _emit_report(ctx)
    (out_dir / "report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    written.append(out_dir / "report.json")
    profile = ctx.classification.profile
    if profile in {"electron", "chromium-browser"}:
        notes = _emit_gui_notes(ctx)
        (out_dir / "NOTES.md").write_text(notes, encoding="utf-8")
        written.append(out_dir / "NOTES.md")
    if profile in {"driver", "system"}:
        stub = _emit_phase2_stub(ctx)
        (out_dir / "package.stub.nix").write_text(stub, encoding="utf-8")
        written.append(out_dir / "package.stub.nix")
        module = _emit_nixos_module_stub(ctx)
        (out_dir / "nixos-module.stub.nix").write_text(module, encoding="utf-8")
        written.append(out_dir / "nixos-module.stub.nix")
        limits = _emit_driver_limitations(ctx)
        (out_dir / "LIMITATIONS.md").write_text(limits, encoding="utf-8")
        written.append(out_dir / "LIMITATIONS.md")
    elif profile in {"gtk", "qt", "fhs-fallback"}:
        stub = _emit_phase2_stub(ctx)
        (out_dir / "package.stub.nix").write_text(stub, encoding="utf-8")
        written.append(out_dir / "package.stub.nix")
    return written


def _header_comment(ctx: EmitContext) -> str:
    return "\n".join(
        [
            f"# Generated by deb2nix {__version__} (profile: {ctx.classification.profile}).",
            "# Review before use. Not intended for publishing into nixpkgs.",
            "# Hash-pinned. Unfree, if any, is explicit via allowUnfreePredicate",
            "# (Tim approval 2026-09-10: Chrome, Edge, VS Code, Grok Bot, DisplayLink EULAs).",
        ]
    )


def _src_attr(ctx: EmitContext) -> str:
    if ctx.src_kind == "url" and ctx.src_url:
        return (
            "  src = fetchurl {\n"
            f"    url = {nix_string(ctx.src_url)};\n"
            f"    hash = {nix_string(ctx.src_hash)};\n"
            "  };"
        )
    return "  src = ./src.deb;"


GUI_USERLAND_EXTRAS = [
    "alsa-lib",
    "at-spi2-core",
    "cairo",
    "cups",
    "dbus",
    "expat",
    "glib",
    "gtk3",
    "libdrm",
    "libGL",
    "libnotify",
    "libsecret",
    "libxkbcommon",
    "mesa",
    "nspr",
    "nss",
    "pango",
    "xorg.libX11",
    "xorg.libXcomposite",
    "xorg.libXdamage",
    "xorg.libXext",
    "xorg.libXfixes",
    "xorg.libXrandr",
    "xorg.libxcb",
]


def _call_args(
    ctx: EmitContext,
    extra_native: list[str] | None = None,
    extra_inputs: list[str] | None = None,
) -> tuple[list[str], list[str], list[str]]:
    """Return (function arguments, nativeBuildInputs, buildInputs exprs)."""
    native = ["autoPatchelfHook", "dpkg", "makeWrapper"]
    for item in extra_native or []:
        if item not in native:
            native.append(item)
    args = ["lib", "stdenv", "dpkg", "autoPatchelfHook", "makeWrapper"]
    for item in extra_native or []:
        if item not in args:
            args.append(item)
    if ctx.src_kind == "url":
        args.append("fetchurl")
    inputs = ["stdenv.cc.cc.lib"]
    extra_args: list[str] = []
    for pkg in list(ctx.mapping.build_inputs) + list(extra_inputs or []):
        top = pkg.split(".", 1)[0]
        if top not in extra_args and top not in args:
            extra_args.append(top)
        inputs.append(pkg)
    seen: set[str] = set()
    args_out: list[str] = []
    for a in args + extra_args:
        if a not in seen:
            seen.add(a)
            args_out.append(a)
    in_seen: set[str] = set()
    inputs_out: list[str] = []
    for i in inputs:
        if i not in in_seen:
            in_seen.add(i)
            inputs_out.append(i)
    return args_out, native, inputs_out


def _fmt_list(items: list[str], indent: int = 4) -> str:
    pad = " " * indent
    if not items:
        return pad + "# (none)"
    return "\n".join(f"{pad}{item}" for item in items)


def _emit_package(ctx: EmitContext) -> str:
    profile = ctx.classification.profile
    if profile == "cli":
        return _emit_cli_package(ctx)
    if profile in {"electron", "chromium-browser"}:
        return _emit_gui_userland_package(ctx)
    return _emit_throwing_package(ctx)


def _unfree_comment(ctx: EmitContext) -> str:
    if not ctx.unfree:
        return ""
    return (
        "\n  # UNFREE: Debian license/section is "
        f"{nix_string(ctx.control.license or ctx.control.section or 'unknown')}.\n"
        "  # Tim approval 2026-09-10 accepted this EULA. The generated flake still\n"
        "  # gates *this pname only* with allowUnfreePredicate (no blanket nixpkgs unfree).\n"
    )


def _ignore_block(ctx: EmitContext) -> str:
    unmapped_ignore = [nix_string(u) for u in ctx.mapping.unmapped]
    if not unmapped_ignore:
        return ""
    return (
        "\n  autoPatchelfIgnoreMissingDeps = [\n"
        + "\n".join(f"    {u}" for u in unmapped_ignore)
        + "\n  ];\n"
    )


def _emit_cli_package(ctx: EmitContext) -> str:
    args, native, inputs = _call_args(ctx)
    arg_block = ",\n  ".join(args)
    input_block = _fmt_list(inputs)
    native_block = _fmt_list(native)
    src = _src_attr(ctx)
    meta_license = ctx.license_expr
    homepage = ctx.control.homepage or ""
    description = ctx.control.synopsis or ctx.pname
    main = ctx.main_program or ctx.pname
    return f"""{_header_comment(ctx)}
{{
  {arg_block},
}}:

stdenv.mkDerivation (finalAttrs: {{
  pname = {nix_string(ctx.pname)};
  version = {nix_string(ctx.control.version)};
{_unfree_comment(ctx)}
{src}

  nativeBuildInputs = [
{native_block}
  ];

  buildInputs = [
{input_block}
  ];
{_ignore_block(ctx)}
  dontConfigure = true;
  dontBuild = true;

  unpackPhase = ''
    runHook preUnpack
    dpkg-deb -x "$src" .
    runHook postUnpack
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p "$out"
    if [ -d usr ]; then
      cp -a usr/. "$out/"
    fi
    if [ -d opt ]; then
      mkdir -p "$out/opt"
      cp -a opt/. "$out/opt/"
    fi
    if [ -d bin ] && [ ! -e "$out/bin" ]; then
      mkdir -p "$out/bin"
      cp -a bin/. "$out/bin/"
    fi
    # Keep Debian bin names; do not invent an Electron wrapper.
    if [ -d "$out/usr/bin" ] && [ ! -e "$out/bin" ]; then
      mv "$out/usr/bin" "$out/bin"
    fi
    runHook postInstall
  '';

  meta = {{
    description = {nix_string(description)};
    homepage = {nix_string(homepage)};
    license = {meta_license};
    platforms = [ {nix_string(ctx.system)} ];
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
    mainProgram = {nix_string(main)};
  }};
}})
"""


def _emit_gui_userland_package(ctx: EmitContext) -> str:
    """Electron / Chromium-browser userland: unpack + autoPatchelf. No --no-sandbox, no FHS."""
    args, native, inputs = _call_args(
        ctx,
        extra_native=["wrapGAppsHook3"],
        extra_inputs=GUI_USERLAND_EXTRAS,
    )
    arg_block = ",\n  ".join(args)
    input_block = _fmt_list(inputs)
    native_block = _fmt_list(native)
    src = _src_attr(ctx)
    meta_license = ctx.license_expr
    homepage = ctx.control.homepage or ""
    description = ctx.control.synopsis or ctx.pname
    main = ctx.main_program or ctx.pname
    profile = ctx.classification.profile
    return f"""{_header_comment(ctx)}
# Userland {profile} expression (Tim 2026-09-10 unfree approval).
# GUI smoke is a separate NixOS+Hyprland step. Sandbox flags are left to the
# operator; this generator does not disable the Chromium sandbox.
# chrome-sandbox is mode 0755 (user namespaces), never setuid, never DKMS.
{{
  {arg_block},
}}:

stdenv.mkDerivation (finalAttrs: {{
  pname = {nix_string(ctx.pname)};
  version = {nix_string(ctx.control.version)};
{_unfree_comment(ctx)}
{src}

  nativeBuildInputs = [
{native_block}
  ];

  buildInputs = [
{input_block}
  ];
{_ignore_block(ctx)}
  dontConfigure = true;
  dontBuild = true;
  dontWrapGApps = true;

  unpackPhase = ''
    runHook preUnpack
    dpkg-deb -x "$src" .
    runHook postUnpack
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p "$out"
    if [ -d usr ]; then
      cp -a usr/. "$out/"
    fi
    if [ -d opt ]; then
      mkdir -p "$out/opt"
      cp -a opt/. "$out/opt/"
    fi
    if [ -d bin ] && [ ! -e "$out/bin" ]; then
      mkdir -p "$out/bin"
      cp -a bin/. "$out/bin/"
    fi
    if [ -d "$out/usr/bin" ] && [ ! -e "$out/bin" ]; then
      mv "$out/usr/bin" "$out/bin"
    fi
    # Debian wrappers often hardcode /opt and /usr.
    if [ -d "$out/bin" ]; then
      for f in "$out/bin"/*; do
        if [ -f "$f" ] && grep -qE '/opt/|/usr/' "$f" 2>/dev/null; then
          substituteInPlace "$f" --replace-quiet /opt/ "$out/opt/" --replace-quiet /usr/ "$out/" || true
        fi
      done
    fi
    find "$out" -name '*.desktop' -type f -print0 2>/dev/null | while IFS= read -r -d '' desk; do
      substituteInPlace "$desk" --replace-quiet /opt/ "$out/opt/" --replace-quiet /usr/ "$out/" || true
    done
    # Never chmod u+s chrome-sandbox from this generator.
    find "$out" -name chrome-sandbox -type f -exec chmod 0755 {{}} \\; || true
    runHook postInstall
  '';

  preFixup = ''
    gappsWrapperArgs+=(
      --set-default ELECTRON_FORCE_IS_PACKAGED 1
    )
  '';

  postFixup = ''
    if [ -n "''${{gappsWrapperArgs-}}" ]; then
      for bin in "$out/bin"/*; do
        if [ -e "$bin" ]; then
          wrapProgram "$bin" "''${{gappsWrapperArgs[@]}}" || true
        fi
      done
    fi
  '';

  meta = {{
    description = {nix_string(description)};
    homepage = {nix_string(homepage)};
    license = {meta_license};
    platforms = [ {nix_string(ctx.system)} ];
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
    mainProgram = {nix_string(main)};
  }};
}})
"""


def _throw_message(ctx: EmitContext) -> str:
    profile = ctx.classification.profile
    reasons = "; ".join(ctx.classification.reasons) or "classifier heuristics"
    if profile in {"driver", "system"}:
        extra = (
            "deb2nix will not emit an expression that loads kernel modules, "
            "installs DKMS, or activates DisplayLink/EVDI. That is intentional."
        )
    elif profile == "electron":
        extra = (
            "Electron profile (Grok Bot / VS Code family) is stubbed until Phase 2. "
            "Do not vendor app2nix's Electron-default template or --no-sandbox. "
            "Do not assume vscode-fhs / buildFHSEnv. "
            "GUI smoke belongs on a NixOS+Hyprland VM."
        )
    elif profile == "chromium-browser":
        extra = (
            "chromium-browser profile (Chrome / Edge family) is stubbed until Phase 2. "
            "Distinct from generic electron: follow nixpkgs google-chrome / microsoft-edge "
            "deb-repack patterns, not grok-bot-flake's bundled-Electron keep. "
            "Unfree + hash-pin. GUI smoke later."
        )
    elif profile in {"gtk", "qt"}:
        extra = (
            f"{profile.upper()} profile is stubbed in Phase 1. "
            "A silent FHS wrap would hide missing toolkit deps."
        )
    else:
        extra = (
            "fhs-fallback refuses to silently emit buildFHSEnv. "
            "Inspect report.json and re-run with --profile after review."
        )
    warnings = " ".join(ctx.classification.warnings)
    return (
        f"deb2nix classified {ctx.pname!r} as profile {profile!r}. {reasons}. {extra} {warnings}"
    ).strip()


def _emit_throwing_package(ctx: EmitContext) -> str:
    args = ["lib"]
    msg = _throw_message(ctx)
    # Nix indented string: escape '' 
    body = msg.replace("''", "'''")
    evidence = json.dumps(ctx.classification.as_dict(), indent=2)
    evidence_comment = "\n".join("# " + line if line else "#" for line in evidence.splitlines())
    return f"""{_header_comment(ctx)}
# Classifier evidence:
{evidence_comment}

{{
  {", ".join(args)},
}}:

throw {nix_indented_string(body, indent="  ")}
"""


def _emit_default(ctx: EmitContext) -> str:
    if ctx.unfree:
        return f"""{_header_comment(ctx)}
{{
  pkgs ? import <nixpkgs> {{
    config.allowUnfreePredicate = pkg: builtins.elem (pkgs.lib.getName pkg) [ {nix_string(ctx.pname)} ];
  }},
}}:

pkgs.callPackage ./package.nix {{ }}
"""
    return f"""{_header_comment(ctx)}
{{ pkgs ? import <nixpkgs> {{ }} }}:

pkgs.callPackage ./package.nix {{ }}
"""


def _emit_flake(ctx: EmitContext) -> str:
    allow = ""
    if ctx.unfree:
        allow = f"""
        config.allowUnfreePredicate = pkg:
          builtins.elem (nixpkgs.lib.getName pkg) [ {nix_string(ctx.pname)} ];
        # Tim 2026-09-10: EULAs accepted. Predicate still pname-scoped (not allowUnfree = true)."""
    else:
        allow = ""
    return f"""{_header_comment(ctx)}
{{
  description = {nix_string(ctx.control.synopsis or ctx.pname + " (generated by deb2nix)")};

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = {{ self, nixpkgs }}:
    let
      system = {nix_string(ctx.system)};
      pkgs = import nixpkgs {{
        inherit system;{allow}
      }};
    in {{
      packages.${{system}} = rec {{
        default = pkgs.callPackage ./package.nix {{ }};
        {nix_string(ctx.pname)} = default;
      }};
    }};
}}
"""


def _emit_phase2_stub(ctx: EmitContext) -> str:
    """Non-evaluated notes for Phase 2 implementers — not a silent FHS wrap."""
    profile = ctx.classification.profile
    notes = {
        "electron": dedent(
            """
            Phase 2 (NixOS + Hyprland GUI VM) — Electron apps (Grok Bot, VS Code):
            - Unpack with dpkg-deb, keep upstream Electron (do not swap nixpkgs electron
              when native .node modules are ABI-locked — see jordangarrison/grok-bot-flake).
            - autoPatchelfHook over the bundled chrome/electron binary and .node modules.
            - wrapGAppsHook3 + makeWrapper; chrome-sandbox handling depends on user namespaces.
            - Do NOT vendor app2nix emit (GTK/Electron single template + --no-sandbox).
            - Patterns: nixpkgs signal-desktop-bin, vscode (not vscode-fhs unless requested),
              nixpkgs#558990 grok-bot draft.
            - Grok Bot 0.47.0 is hash-pinned in fixtures/MATRIX.md and examples/grok-bot/.
            - Hash-pin fetchurl; allowUnfreePredicate for this pname only.
            """
        ).strip(),
        "chromium-browser": dedent(
            """
            Phase 2 — Chromium browsers (Chrome, Edge), distinct from electron:
            - nixpkgs google-chrome / microsoft-edge: fetchurl .deb, commandLineArgs, unfree.
            - Widevine, sandbox, GTK wrap — not app.asar / electron ABI.
            - Do not silently pick *-fhs. Hash-pin; allowUnfreePredicate.
            """
        ).strip(),
        "gtk": "wrapGAppsHook3, gtk3/gtk4, gdk-pixbuf loaders, dconf. No FHS unless mapping fails honestly.",
        "qt": "qt5/qt6.qtbase, wrapQtAppsHook. Prefer autoPatchelfHook over FHS.",
        "driver": "Phase 3 prep. Synaptics EULA accepted 2026-09-10; still never insmod/DKMS. See LIMITATIONS.md + nixos-module.stub.nix.",
        "system": "udev/firmware/systemd units need NixOS modules, not a user package install.",
        "fhs-fallback": "Only emit buildFHSEnv after an explicit --profile fhs-fallback *and* a human review of unmapped libs. Phase 1 still throws.",
    }
    note = notes.get(profile, "")
    return f"""{_header_comment(ctx)}
# This file is documentation for a future profile implementation.
# package.nix throws until the profile is fully implemented.
#
# profile: {profile}
# subtype: {ctx.classification.subtype}
#
{chr(10).join('# ' + line if line else '#' for line in note.splitlines())}
#
# Suggested fetch:
#   src = fetchurl {{ url = "..."; hash = {nix_string(ctx.src_hash)}; }};
"""


def _emit_gui_notes(ctx: EmitContext) -> str:
    return dedent(
        f"""\
        # {ctx.pname} — userland notes

        Profile: `{ctx.classification.profile}`. Unfree EULA accepted 2026-09-10 (Tim).

        `package.nix` is a **userland** unpack + `autoPatchelfHook` + GApps wrap. It is
        hash-pinned and uses `allowUnfreePredicate` for this pname only.

        Still out of scope for this generator:

        - GUI smoke (needs NixOS + Hyprland). `nix build` here is not a display test.
        - `--no-sandbox` (app2nix default; we will not).
        - `vscode-fhs` / silent `buildFHSEnv`.
        - `chrome-sandbox` setuid. Mode 0755; relies on user namespaces.
        - Publishing to public nixpkgs.

        Hash: `{ctx.src_hash}`
        """
    )


def _emit_nixos_module_stub(ctx: EmitContext) -> str:
    pname = ctx.pname
    return f"""{_header_comment(ctx)}
# NixOS module stub — DisplayLink / kernel drivers.
# This file is NOT imported by package.nix. It documents how a human would
# wire nixpkgs hardware.video.displaylink after reviewing LIMITATIONS.md.
# deb2nix will not insmod, will not run DKMS, will not modify host machines.

{{ config, lib, pkgs, ... }}:

{{
  # Unfree EULA accepted 2026-09-10 (Tim). Still do not enable this blindly:
  # EVDI is a kernel module. Enable only on a NixOS host you intend to reboot.
  #
  # nixpkgs: hardware.video.displaylink.enable
  #          + evdi + requireFile for the vendor blob on some versions.
  #
  # Example (commented — not activated by generating this tree):
  #
  # nixpkgs.config.allowUnfreePredicate = pkg:
  #   builtins.elem (lib.getName pkg) [ {nix_string(pname)} "displaylink" "evdi" ];
  # hardware.video.displaylink.enable = false;
  # boot.extraModulePackages = [ ]; # do not add evdi from this stub

  assertions = [
    {{
      assertion = true;
      message = {nix_string("deb2nix DisplayLink stub: kernel/DKMS not enabled")};
    }}
  ];
}}
"""


def _emit_driver_limitations(ctx: EmitContext) -> str:
    reasons = "\n".join(f"- {r}" for r in ctx.classification.reasons) or "- (see report.json)"
    return f"""# LIMITATIONS — `{ctx.pname}` ({ctx.classification.profile})

**Success criterion (Phase 1/3 prep):** honest stub + this report. A full
DisplayLink *runtime* needs EVDI/DKMS on NixOS; that is **not** done here.

## Policy

- Tim approval 2026-09-10 accepted the Synaptics/DisplayLink EULA and unfree.
- deb2nix still **must not** `insmod`, run DKMS, load `evdi`, or change Tim's machines.
- Analysis + generate + `nix build` of *userland* expressions only.
- Do not publish this expression to public nixpkgs.

## Classifier evidence

{reasons}

Hash: `{ctx.src_hash}`
Depends: `{ctx.control.depends or "(none)"}`

## What nixpkgs already has

- `hardware.video.displaylink` (NixOS module)
- `evdi` kernel package
- Often `requireFile` + unfree for the vendor blob

See `nixos-module.stub.nix` (commented; not enabled).

## What this generate step produced

- `package.nix` **throws** — will not unpack into a fake "it works" FHS env.
- `LIMITATIONS.md` (this file)
- `nixos-module.stub.nix` — documentation only

If userspace binaries exist in the `.deb` (DisplayLinkManager, udev rules),
they are useless without the kernel module. Patchelf-only userland is not
claimed as a working driver.
"""


def _emit_report(ctx: EmitContext) -> dict:
    return {
        "deb2nix": __version__,
        "pname": ctx.pname,
        "version": ctx.control.version,
        "architecture": ctx.control.architecture,
        "nixSystem": ctx.system,
        "profile": ctx.classification.as_dict(),
        "unfree": ctx.unfree,
        "licenseExpr": ctx.license_expr,
        "source": {
            "kind": ctx.src_kind,
            "url": ctx.src_url,
            "filename": ctx.src_filename,
            "hash": ctx.src_hash,
        },
        "control": {
            "package": ctx.control.package,
            "homepage": ctx.control.homepage,
            "maintainer": ctx.control.maintainer,
            "depends": ctx.control.depends,
            "section": ctx.control.section,
            "license": ctx.control.license,
            "description": ctx.control.synopsis,
        },
        "mapping": {
            "locateAvailable": ctx.mapping.locate_available,
            "buildInputs": ctx.mapping.build_inputs,
            "unmapped": ctx.mapping.unmapped,
            "bundled": ctx.mapping.bundled,
            "libs": [
                {
                    "lib": m.lib,
                    "pkg": m.pkg,
                    "source": m.source,
                    "note": m.note,
                }
                for m in ctx.mapping.mapped
            ],
        },
        "needed": ctx.needed,
        "binaries": ctx.binaries,
        "mainProgram": ctx.main_program,
        "constraints": {
            "noPublicNixpkgsPublish": True,
            "unfreeExplicit": True,
            "hashPinned": True,
            "honestFailureOverSilentFhs": True,
            "noDisplayLinkKernelLoad": True,
        },
    }
