# Generated by deb2nix 0.1.0 (profile: fhs-fallback).
# Review before use. Not intended for publishing into nixpkgs.
# Hash-pinned. Unfree, if any, is explicit via allowUnfreePredicate
# (Tim approval 2026-09-10: Chrome, Edge, VS Code, Grok Bot, DisplayLink EULAs).
# This file is documentation for a future profile implementation.
# package.nix throws until the profile is fully implemented.
#
# profile: fhs-fallback
# subtype: None
#
# Only emit buildFHSEnv after an explicit --profile fhs-fallback *and* a human review of unmapped libs. Phase 1 still throws.
#
# Suggested fetch:
#   src = fetchurl { url = "..."; hash = "sha256-+DMAkohI8vdgX/hDhGcmcBnHzFGB7Iueq8fx4Fy/rL4="; };
