# Generated by deb2nix 0.1.0 (profile: fhs-fallback).
# Review before use. Not intended for publishing into nixpkgs.
# Hash-pinned. Unfree, if any, is explicit via allowUnfreePredicate
# (Tim approval 2026-09-10: Chrome, Edge, VS Code, Grok Bot, DisplayLink EULAs).
# Classifier evidence:
# {
#   "profile": "fhs-fallback",
#   "confidence": "low",
#   "reasons": [
#     "layout does not match cli/electron/chromium-browser/gtk/qt/driver heuristics"
#   ],
#   "evidence": {
#     "unmapped": []
#   },
#   "subtype": null,
#   "warnings": [
#     "Honest failure: deb2nix will not silently wrap this in buildFHSEnv. Inspect report.json."
#   ]
# }

{
  lib,
}:

throw "deb2nix classified 'synaptics-repository-keyring' as profile 'fhs-fallback'. layout does not match cli/electron/chromium-browser/gtk/qt/driver heuristics. fhs-fallback refuses to silently emit buildFHSEnv. Inspect report.json and re-run with --profile after review. Honest failure: deb2nix will not silently wrap this in buildFHSEnv. Inspect report.json."
