# Generated by deb2nix 0.1.0 (profile: electron).
# Review before use. Not intended for publishing into nixpkgs.
# Hash-pinned src. Review before use.
# import <nixpkgs> picks up ~/.config/nixpkgs/config.nix (allowUnfree, etc.).
{ pkgs ? import <nixpkgs> { } }:

pkgs.callPackage ./package.nix { }
