# Generated by deb2nix 0.1.0 (profile: electron).
# Review before use. Not intended for publishing into nixpkgs.
# Hash-pinned src. Review before use.
{
  description = "grok-bot";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      # No config here: flakes do not inherit NixOS allowUnfree.
      # Consume package.nix from NixOS, or: NIXPKGS_ALLOW_UNFREE=1 nix build --impure
      pkgs = import nixpkgs { inherit system; };
    in {
      packages.${system} = rec {
        default = pkgs.callPackage ./package.nix { };
        "grok-bot" = default;
      };
    };
}
