# Generated by deb2nix 0.1.0 (profile: electron).
# Review before use. Not intended for publishing into nixpkgs.
# Hash-pinned src. Review before use.
# Userland electron expression: unpack + autoPatchelf + GApps wrap.
# Does not disable the Chromium sandbox. *-sandbox files are mode 0755.
# Qt5/Qt6 are not in buildInputs (hook conflict); sonames ignored if present.
{
  lib,
  stdenv,
  dpkg,
  autoPatchelfHook,
  makeWrapper,
  wrapGAppsHook3,
  fetchurl,
  libx11,
  libxcomposite,
  libxdamage,
  libxext,
  libxfixes,
  libxrandr,
  alsa-lib,
  at-spi2-atk,
  at-spi2-core,
  cairo,
  cups,
  dbus,
  expat,
  mesa,
  glib,
  gtk3,
  nspr,
  nss,
  pango,
  systemd,
  libxcb,
  libxkbcommon,
  libdrm,
  libGL,
  libnotify,
  libsecret,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "grok-bot";
  version = "0.47.0";
  src = fetchurl {
    url = "https://downloads.cursor.com/grokbot/stable/c1e7d7a46549956d25f53e9c0b9f59666e03aa3a/linux/x64/grok-bot_0.47.0_amd64.deb";
    hash = "sha256-EcoPUaU1uXr1GjUq35wPns0uGwQwpprpRRtoinoGWAg=";
  };

  nativeBuildInputs = [
    autoPatchelfHook
    dpkg
    makeWrapper
    wrapGAppsHook3
  ];

  buildInputs = [
    stdenv.cc.cc.lib
    libx11
    libxcomposite
    libxdamage
    libxext
    libxfixes
    libxrandr
    alsa-lib
    at-spi2-atk
    at-spi2-core
    cairo
    cups
    dbus
    expat
    mesa
    glib
    gtk3
    nspr
    nss
    pango
    systemd
    libxcb
    libxkbcommon
    libdrm
    libGL
    libnotify
    libsecret
  ];

  dontConfigure = true;
  dontBuild = true;
  dontWrapGApps = true;
  dontWrapQtApps = true;

  unpackPhase = ''
    runHook preUnpack
    dpkg-deb --fsys-tarfile "$src" | tar -x --no-same-owner --no-same-permissions
    runHook postUnpack
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p "$out"
    if [ -d usr ]; then
      cp -a usr/. "$out/"
    fi
    if [ -d opt ]; then
      mkdir -p "$out/opt"
      cp -a opt/. "$out/opt/"
    fi
    if [ -d bin ] && [ ! -e "$out/bin" ]; then
      mkdir -p "$out/bin"
      cp -a bin/. "$out/bin/"
    fi
    if [ -d "$out/usr/bin" ] && [ ! -e "$out/bin" ]; then
      mv "$out/usr/bin" "$out/bin"
    fi
    # Debian .debs often ship absolute /opt and /usr symlinks; retarget into $out.
    find "$out" -type l -print0 2>/dev/null | while IFS= read -r -d $'\0' link; do
      t="$(readlink "$link" || true)"
      case "$t" in
        /opt/*)
          ln -sfn "$out$t" "$link" || true
          ;;
        /usr/*)
          ln -sfn "$out''${t#/usr}" "$link" || true
          ;;
      esac
    done
    # Rewrite text wrappers only. substituteInPlace on an ELF corrupts it.
    if [ -d "$out/bin" ]; then
      for f in "$out/bin"/*; do
        [ -f "$f" ] && [ ! -L "$f" ] || continue
        magic="$(head -c 4 "$f" 2>/dev/null || true)"
        if [ "$magic" = $'\x7fELF' ]; then
          continue
        fi
        if grep -qE '/opt/|/usr/' "$f" 2>/dev/null; then
          substituteInPlace "$f" --replace-quiet /opt/ "$out/opt/" --replace-quiet /usr/ "$out/" || true
        fi
      done
    fi
    find "$out" -name '*.desktop' -type f -print0 2>/dev/null | while IFS= read -r -d $'\0' desk; do
      substituteInPlace "$desk" --replace-quiet /opt/ "$out/opt/" --replace-quiet /usr/ "$out/" || true
    done
    # Chromium helper binaries named *-sandbox must not be setuid in the Nix store.
    find "$out" -type f \( -name chrome-sandbox -o -name '*-sandbox' \) -exec chmod 0755 {} \; || true
    mkdir -p "$out/bin"
    # If the .deb had no usr/bin, expose executables from opt/share by basename.
    if [ -z "$(find "$out/bin" -mindepth 1 -maxdepth 1 \( -type f -o -xtype f \) -print -quit 2>/dev/null)" ]; then
      find "$out/opt" "$out/share" -maxdepth 4 -type f -executable \
        ! -name '*.so' ! -name '*.so.*' ! -name '*-sandbox' ! -name '*crashpad*' \
        2>/dev/null | while IFS= read -r exe; do
        [ -n "$exe" ] || continue
        ln -sfn "$exe" "$out/bin/$(basename "$exe")" || true
      done
    fi
    runHook postInstall
  '';

  preFixup = ''
    gappsWrapperArgs+=(
      --set-default ELECTRON_FORCE_IS_PACKAGED 1
    )
  '';

  postFixup = ''
    if [ -n "''${gappsWrapperArgs-}" ]; then
      for bin in "$out/bin"/*; do
        if [ -e "$bin" ] && [ -x "$bin" ]; then
          wrapProgram "$bin" "''${gappsWrapperArgs[@]}" || true
        fi
      done
    fi
  '';

  meta = {
    description = "grok-bot";
    homepage = "https://cursor.com";
    license = lib.licenses.free;
    platforms = [ "x86_64-linux" ];
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
    mainProgram = "grok-bot";
  };
})
