# Generated by deb2nix 0.1.0 (profile: electron).
# Review before use. Not intended for publishing into nixpkgs.
# Hash-pinned. Unfree, if any, is explicit via allowUnfreePredicate
# (Tim approval 2026-09-10: Chrome, Edge, VS Code, Grok Bot, DisplayLink EULAs).
# Userland electron expression (Tim 2026-09-10 unfree approval).
# GUI smoke is a separate NixOS+Hyprland step. Sandbox flags are left to the
# operator; this generator does not disable the Chromium sandbox.
# chrome-sandbox is mode 0755 (user namespaces), never setuid, never DKMS.
# Qt5/Qt6 are not in buildInputs (hook conflict); sonames ignored if present.
{
  lib,
  stdenv,
  dpkg,
  autoPatchelfHook,
  makeWrapper,
  wrapGAppsHook3,
  fetchurl,
  xorg,
  alsa-lib,
  at-spi2-atk,
  at-spi2-core,
  cairo,
  cups,
  dbus,
  expat,
  mesa,
  glib,
  gtk3,
  nspr,
  nss,
  pango,
  systemd,
  libxkbcommon,
  libdrm,
  libGL,
  libnotify,
  libsecret,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "grok-bot";
  version = "0.47.0";

  # UNFREE: Debian license/section is "unknown".
  # Tim approval 2026-09-10 accepted this EULA. The generated flake still
  # gates *this pname only* with allowUnfreePredicate (no blanket nixpkgs unfree).

  src = fetchurl {
    url = "https://downloads.cursor.com/grokbot/stable/c1e7d7a46549956d25f53e9c0b9f59666e03aa3a/linux/x64/grok-bot_0.47.0_amd64.deb";
    hash = "sha256-EcoPUaU1uXr1GjUq35wPns0uGwQwpprpRRtoinoGWAg=";
  };

  nativeBuildInputs = [
    autoPatchelfHook
    dpkg
    makeWrapper
    wrapGAppsHook3
  ];

  buildInputs = [
    stdenv.cc.cc.lib
    xorg.libX11
    xorg.libXcomposite
    xorg.libXdamage
    xorg.libXext
    xorg.libXfixes
    xorg.libXrandr
    alsa-lib
    at-spi2-atk
    at-spi2-core
    cairo
    cups
    dbus
    expat
    mesa
    glib
    gtk3
    nspr
    nss
    pango
    systemd
    xorg.libxcb
    libxkbcommon
    libdrm
    libGL
    libnotify
    libsecret
  ];

  dontConfigure = true;
  dontBuild = true;
  dontWrapGApps = true;
  dontWrapQtApps = true;

  unpackPhase = ''
    runHook preUnpack
    dpkg-deb --fsys-tarfile "$src" | tar -x --no-same-owner --no-same-permissions
    runHook postUnpack
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p "$out"
    if [ -d usr ]; then
      cp -a usr/. "$out/"
    fi
    if [ -d opt ]; then
      mkdir -p "$out/opt"
      cp -a opt/. "$out/opt/"
    fi
    if [ -d bin ] && [ ! -e "$out/bin" ]; then
      mkdir -p "$out/bin"
      cp -a bin/. "$out/bin/"
    fi
    if [ -d "$out/usr/bin" ] && [ ! -e "$out/bin" ]; then
      mv "$out/usr/bin" "$out/bin"
    fi
    # Debian .debs often ship absolute /opt and /usr symlinks; retarget into $out.
    find "$out" -type l -print0 2>/dev/null | while IFS= read -r -d $'\0' link; do
      t="$(readlink "$link" || true)"
      case "$t" in
        /opt/*)
          ln -sfn "$out$t" "$link" || true
          ;;
        /usr/*)
          ln -sfn "$out''${t#/usr}" "$link" || true
          ;;
      esac
    done
    # Debian wrappers often hardcode /opt and /usr.
    if [ -d "$out/bin" ]; then
      for f in "$out/bin"/*; do
        if [ -f "$f" ] && grep -qE '/opt/|/usr/' "$f" 2>/dev/null; then
          substituteInPlace "$f" --replace-quiet /opt/ "$out/opt/" --replace-quiet /usr/ "$out/" || true
        fi
      done
    fi
    find "$out" -name '*.desktop' -type f -print0 2>/dev/null | while IFS= read -r -d $'\0' desk; do
      substituteInPlace "$desk" --replace-quiet /opt/ "$out/opt/" --replace-quiet /usr/ "$out/" || true
    done
    # Never chmod u+s chrome-sandbox from this generator.
    find "$out" -name chrome-sandbox -type f -exec chmod 0755 {} \; || true
    mkdir -p "$out/bin"
    if [ -z "$(find "$out/bin" -mindepth 1 -maxdepth 1 \( -type f -o -xtype f \) -print -quit 2>/dev/null)" ]; then
      exe="$(find "$out/opt" "$out/share" -maxdepth 3 -type f -name "grok-bot" 2>/dev/null | head -n 1 || true)"
      if [ -n "$exe" ]; then
        ln -s "$exe" "$out/bin/grok-bot" || true
      fi
    fi
    runHook postInstall
  '';

  preFixup = ''
    gappsWrapperArgs+=(
      --set-default ELECTRON_FORCE_IS_PACKAGED 1
    )
  '';

  postFixup = ''
    if [ -n "''${gappsWrapperArgs-}" ]; then
      for bin in "$out/bin"/*; do
        if [ -e "$bin" ]; then
          wrapProgram "$bin" "''${gappsWrapperArgs[@]}" || true
        fi
      done
    fi
  '';

  meta = {
    description = "grok-bot";
    homepage = "https://cursor.com";
    license = lib.licenses.unfree;
    platforms = [ "x86_64-linux" ];
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
    mainProgram = "grok-bot";
  };
})
